### ISSUE TITLE
`blurhash_ffi` - `flutter_blurhash` | Bad state? 

### ISSUE THREAD

**Issue by felipecastrosales** [folksable/blurhash_ffi#6]
Hello, 

I currently use `flutter_blurhash` in my projects, and sometimes I come across the `Bad state`, as you can see [here in this issue](https://github.com/fluttercommunity/flutter_blurhash/issues/40).

I quickly analyzed the package, and the widget implementation resembles the above. 

I would like to know if there is something similar in this package (the issue cited); or if any treatment was carried out for this - and if so, which one? 

Thanks

**Comment by dhikshith12** [comment]
Yes, i copied the widget implementation from `flutter_blurhash` for easy migration from `flutter_blurhash` to `blurhash_ffi`, but also included this [pull request](https://github.com/fluttercommunity/flutter_blurhash/pull/47) which you also [commented](https://github.com/fluttercommunity/flutter_blurhash/pull/47#issuecomment-1630817806) on.

you mentioned that Slivers might be causing that issue for you? are you still facing the issue after including that [pr](https://github.com/fluttercommunity/flutter_blurhash/pull/47) in your code (asking because i have not faced such error after including the pr in `blurhash_ffi`)?

See this stateless widget where i used `errorBuilder` as proposed in the pr.
https://github.com/folksable/blurhash_ffi/blob/2649abd1d483dbc54e6c343c17f41905710ab76a/lib/blurhashffi_widget.dart#L153

**Comment by felipecastrosales** [comment]
Hey @dhikshith12, I used `blurhash_ffi` again in my project, because it looks very interesting to me. 

But in my tests, I saw that the `Bad State` problem persists. Log evidence: 

![image](https://github.com/folksable/blurhash_ffi/assets/59374587/ceb82eea-57d9-4889-b689-12a4bb686061)

---

Have you any suggestions to this? Is relatively hard to reproduce, unfortunately.

**Comment by felipecastrosales** [comment]
Other question, I see that the plugin requires one more updated NDK version when build, something like [this](https://stackoverflow.com/questions/73032815/flutter-android-one-or-more-plugins-require-a-higher-android-ndk-version).

This is really intentional and this can affect users? 

Best regards, @dhikshith12.

**Comment by dhikshith12** [comment]
Hello, @felipecastrosales, The Bad State issue you mentioned is interesting, and I thought that [pr](https://github.com/fluttercommunity/flutter_blurhash/pull/47) would solve this issue, so I added the pr. However, as you said, this issue persists like in the other package, and I cannot think of a solution because I don't understand what's causing it.

the plugin requires NDK version 25.2.9519653 to compile the native part while building for Android and it's an expected behavior, it's recommended to add this version in your build.gradle of your android/app, However, I did experience any adverse effects by not adding this ndkVersion in your android/app project apart from a console message.

for my app using this package, the issues pointed out are not fatal and infrequent so it's not a priority.

Good to hear this, please update this thread if you find anything interesting/cause/a way to solve it.

Cheers.

**Comment by felipecastrosales** [comment]
Hey @dhikshith12, I updated the issue with a minimal reproducible example, check below: 

- https://github.com/fluttercommunity/flutter_blurhash/issues/40#issuecomment-1769673892

**Comment by felipecastrosales** [comment]
This is a behavior that occurs in another package, not this one. I think I can close this issue.
