### ISSUE TITLE
Get blurhash from image path

### ISSUE THREAD

**Issue by csbence10** [folksable/blurhash_ffi#8]
Hello,

I wanted to ask if it's feasible to obtain the blurhash string from an image path. In our app, the client calculates the hash before uploading a new profile picture. Currently, we're utilizing the blurhash_dart package for both encoding and decoding. I'd be open to switching to this package if it offers better performance.

In any case, great work!

**Comment by dhikshith12** [comment]
Hello @csbence10,

Yes, it is possible to obtain blurhash string from various sources including asset images, all you need to encode is an instance of an [`ImageProvider`](https://api.flutter.dev/flutter/painting/ImageProvider-class.html) (no image package is required), as `ImageProvider` is one of the core classes of flutter, you can obtain one using any of [`AssetBundleImageProvider`](https://api.flutter.dev/flutter/painting/AssetBundleImageProvider-class.html), [`FileImage`](https://api.flutter.dev/flutter/painting/FileImage-class.html), [`MemoryImage`](https://api.flutter.dev/flutter/painting/MemoryImage-class.html), [`NetworkImage`](https://api.flutter.dev/flutter/painting/NetworkImage-class.html), [`ResizeImage`](https://api.flutter.dev/flutter/painting/ResizeImage-class.html), [`ScrollAwareImageProvider`](https://api.flutter.dev/flutter/widgets/ScrollAwareImageProvider-class.html).

In your case, I'm assuming you have a `File` object of an image, in that case, `FileImage` as the ImageProvder should work fine, or if you are working with a Local Image, you can use an `AssetImage` which implements `ImageProvider`.

```dart
import 'package:blurhash_ffi/blurhash_ffi.dart';

/// Encoding a blurhash from an image provider
///
/// You can use any ImageProvider you want, including NetworkImage, FileImage, MemoryImage, AssetImage, etc.
final imageProvider = NetworkImage('https://picsum.photos/512');
final imageProvider2 = AssetImage('assets/image.jpg');

/// Signature
/// static Future<String> encode(
///   ImageProvider imageProvider, {
///   int componentX = 4,
///   int componentY = 3,
/// })
/// may throw `BlurhashFFIException` if encoding fails.
final String blurHash = await BlurhashFFI.encode(imageProvider);
```

I also used blurhash_dart previously and found that it was freezing the UI, and using it in a separate isolate also didn't help with performance, that's why I wrote this package, It solved the problem in my app (fast and not freezing UI thread), hope it works in your apps as well.

**Cheers, Have a Good Day**
